<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LLLGMOJ" failures="4" tests="14" name="RetryMulitple" time="0.161" errors="0" timestamp="26 Oct 2022 03:09:15 GMT">
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1 on [Test001 passed=0 failed=0 skipped=0]" time="0.04">
    <skipped/>
  </testcase> <!-- Test1 on [Test001 passed=0 failed=0 skipped=0] -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1 on [Test001 passed=0 failed=0 skipped=0]" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 on [Test001 passed=0 failed=0 skipped=0] -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1 on [Test001 passed=0 failed=0 skipped=0]" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test1(Test001.java:17)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 on [Test001 passed=0 failed=0 skipped=0] -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2 on [Test001 passed=0 failed=0 skipped=0]" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 on [Test001 passed=0 failed=0 skipped=0] -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2 on [Test001 passed=0 failed=0 skipped=0]" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 on [Test001 passed=0 failed=0 skipped=0] -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2 on [Test001 passed=0 failed=0 skipped=0]" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test2(Test001.java:30)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 on [Test001 passed=0 failed=0 skipped=0] -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test002.Test1(Test002.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test002.Test2(Test002.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test3" time="0.002">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test3" time="0.006"/>
</testsuite> <!-- RetryMulitple -->
